package com.myspace.test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int godine;
	private java.lang.String ime;
	private int plata;

	public Person() {
	}

	public int getGodine() {
		return this.godine;
	}

	public void setGodine(int godine) {
		this.godine = godine;
	}

	public java.lang.String getIme() {
		return this.ime;
	}

	public void setIme(java.lang.String ime) {
		this.ime = ime;
	}

	public int getPlata() {
		return this.plata;
	}

	public void setPlata(int plata) {
		this.plata = plata;
	}

	public Person(int godine, java.lang.String ime, int plata) {
		this.godine = godine;
		this.ime = ime;
		this.plata = plata;
	}

}